# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = kkm_test
DESTDIR = ../../../builds/lib
QT += core widgets gui serialport
CONFIG += debug
DEFINES += linux QT_DLL QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug
LIBPATH += $$DESTDIR
LIBS    += -lkkm_driver
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(../linux/kkm_test.pri)
QMAKE_CXXFLAGS += -std=c++11
